/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Sender;
import bl.SenderTableModel;
import bl.SenderTableRenderer;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoZuG
 */
public class RadioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioGUI
     */
    private SenderTableModel model = new SenderTableModel();
    private SenderTableRenderer renderer = new SenderTableRenderer();
    private File f = new File("src\\data.bin");

    public RadioGUI() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        radioTable.setModel(model);
        radioTable.setDefaultRenderer(Object.class, renderer);
        itemHide.setVisible(false);
        itemShow.setVisible(false);
        model.load(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        itemHinzufügen = new javax.swing.JMenuItem();
        itemHide = new javax.swing.JMenuItem();
        itemShow = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        radioTable = new javax.swing.JTable();

        itemHinzufügen.setText("hinzufügen");
        itemHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHinzufügenActionPerformed(evt);
            }
        });
        popupmenu.add(itemHinzufügen);

        itemHide.setText("Band verstecken");
        itemHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHideActionPerformed(evt);
            }
        });
        popupmenu.add(itemHide);

        itemShow.setText("Band anzeigen");
        itemShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemShowActionPerformed(evt);
            }
        });
        popupmenu.add(itemShow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setComponentPopupMenu(popupmenu);

        radioTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        radioTable.setComponentPopupMenu(popupmenu);
        jScrollPane1.setViewportView(radioTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHinzufügenActionPerformed
        SenderDlg dlg = new SenderDlg(this, true);
        dlg.setVisible(true);
        if (dlg.isOk()) {
            model.addSender(new Sender(dlg.getSendername(), dlg.getFrequenz(), dlg.getBand()));

            if (model.getRowCount() > 0) {
                itemHide.setVisible(true);
                itemShow.setVisible(true);
            }
        }
    }//GEN-LAST:event_itemHinzufügenActionPerformed

    private void itemHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHideActionPerformed
        if (model.getRowCount() > 0) {
            model.setShow(false);
            model.updateTable();
        }
    }//GEN-LAST:event_itemHideActionPerformed

    private void itemShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemShowActionPerformed
        if (model.getRowCount() > 0) {
            model.setShow(true);
            model.updateTable();
        }
    }//GEN-LAST:event_itemShowActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            model.save(f);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "save error!");
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RadioGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RadioGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RadioGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemHide;
    private javax.swing.JMenuItem itemHinzufügen;
    private javax.swing.JMenuItem itemShow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JTable radioTable;
    // End of variables declaration//GEN-END:variables
}
